### ISSUE TITLE
Missing envlight when running the first step of training after following instructions

### ISSUE THREAD

**Issue by joseph-schwartz** [deepseek-ai/DreamCraft3D#15]
(venv) root@b755cfdb0b39:/workspace/DreamCraft3D# python launch.py --config configs/dreamcraft3d-coarse-nerf.yaml --train system.prompt_processor.prompt="$prompt" data.image_path="$image_path"
Traceback (most recent call last):
  File "/workspace/DreamCraft3D/launch.py", line 252, in <module>
    main(args, extras)
  File "/workspace/DreamCraft3D/launch.py", line 74, in main
    import threestudio
  File "/workspace/DreamCraft3D/threestudio/__init__.py", line 36, in <module>
    from . import data, models, systems
  File "/workspace/DreamCraft3D/threestudio/models/__init__.py", line 1, in <module>
    from . import (
  File "/workspace/DreamCraft3D/threestudio/models/exporters/__init__.py", line 1, in <module>
    from . import base, mesh_exporter
  File "/workspace/DreamCraft3D/threestudio/models/exporters/base.py", line 6, in <module>
    from threestudio.models.materials.base import BaseMaterial
  File "/workspace/DreamCraft3D/threestudio/models/materials/__init__.py", line 1, in <module>
    from . import (
  File "/workspace/DreamCraft3D/threestudio/models/materials/pbr_material.py", line 4, in <module>
    import envlight
ModuleNotFoundError: No module named 'envlight'

**Comment by MrTornado24** [comment]
Hi, did you install envlight by `pip install git+https://github.com/ashawkey/envlight.git`?

**Comment by joseph-schwartz** [comment]
Thank you, that is what I ended up finding, thank you for the help!  I should have closed this when I found it.
